pretrain: 
seed: 1024
data:
    dataset: gym99
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 2
    workers: 16
    num_classes: 99
    image_tmpl: 'img_{:05d}.jpg'
    val_list: 'lists/gym99/val_frames.txt' #
    label_list: 'lists/gym99_labels.csv'
    index_bias: 1
    input_size: 224
    random_shift: False
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 # probability of an element to be zeroed
    emb_dropout: 0.0 # probability of embedding to be zeroed
    type: clip_gym99
    sim_header: "Transf"   #Transf   meanP  LSTM  Conv_1D  Transf_cls
    joint: False
    describe:
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1