pretrain: exp/clip_gym99/ViT-B/32/gym99/model_best.pt
seed: 1024
data:
    dataset: gym99
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 16
    workers: 16
    gpus: 2
    num_classes: 15
    image_tmpl: 'img_{:05d}.jpg'
    val_list: 'lists/gym99/val_set_frames.txt' #
    label_list: 'lists/gym99_set_labels.csv'
    index_bias: 1
    input_size: 224
    random_shift: False
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 
    emb_dropout: 0.0
    bn_momentum: 0.1
    consensus_type: avg
    type: clip_gym99
    sim_header: "Transf"   #Transf   meanP  LSTM  Conv_1D  Transf_cls
    joint: False
    describe:
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1